"""Tests for the v0.2.3 S3A scale-import probe (small libraries only).

Every test runs inside pytest ``tmp_path`` roots with PDFs of at most 10
pages generated by ``scripts/generate_scale_pdf``.  The probe is exercised
through its ``main`` entry in-process (no subprocess residue); the 300/1000
page baselines stay out of the routine suite by design.
"""

from __future__ import annotations

import json
import socket
from pathlib import Path

import pytest

from scripts import run_scale_import_probe as probe
from scripts.generate_scale_pdf import build_scale_pdf

REQUIRED_METRIC_FIELDS = {
    "test_name",
    "duration_seconds",
    "pdf_pages",
    "peak_working_set_bytes",
    "disk_free_start_bytes",
    "disk_free_end_bytes",
    "status",
}


def _read_jsonl(path: Path) -> list[dict[str, object]]:
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def _make_pdf(root: Path, name: str = "probe-5.pdf", pages: int = 5) -> Path:
    target = root / name
    build_scale_pdf(target, pages=pages, document_id="PROBE")
    return target


def _import(root: Path, pdf: Path, *extra: str) -> int:
    return probe.main(
        ["--root", str(root), "import", "--pdf", str(pdf), *extra]
    )


def test_small_import_end_to_end(tmp_path: Path) -> None:
    root = tmp_path / "case"
    pdf = _make_pdf(tmp_path)

    assert _import(root, pdf, "--expect-pages", "5") == 0
    assert probe.main(["--root", str(root), "status"]) == 0
    assert (
        probe.main(
            [
                "--root", str(root),
                "read-pages", "--pages", "1,3,5", "--expect-token", "PROBE",
            ]
        )
        == 0
    )
    assert (
        probe.main(
            [
                "--root", str(root),
                "search", "--query", "TOKEN PROBE-000003", "--expect-page", "3",
            ]
        )
        == 0
    )
    assert probe.main(["--root", str(root), "list-pages"]) == 0
    assert probe.main(["--root", str(root), "consistency"]) == 0

    status_records = [
        r for r in _read_jsonl(root / "probe-results.jsonl") if r["phase"] == "status"
    ]
    assert status_records[-1]["pages"] == 5
    assert status_records[-1]["fts"] == 5
    assert status_records[-1]["png_files"] == 5


def test_formal_root_is_rejected(tmp_path: Path) -> None:
    pdf = _make_pdf(tmp_path)
    exit_code = probe.main(
        ["--root", str(probe.FORMAL_PROJECT_ROOT), "import", "--pdf", str(pdf)]
    )
    assert exit_code == 2


def test_formal_pdf_input_is_rejected(tmp_path: Path) -> None:
    exit_code = probe.main(
        [
            "--root", str(tmp_path / "case"),
            "import", "--pdf", str(probe.FORMAL_PROJECT_ROOT / "data" / "raw" / "x.pdf"),
        ]
    )
    assert exit_code == 2


def test_import_failure_returns_nonzero(tmp_path: Path) -> None:
    broken = tmp_path / "broken.pdf"
    broken.write_bytes(b"not a real pdf")

    exit_code = _import(tmp_path / "case", broken)

    assert exit_code != 0
    records = _read_jsonl(tmp_path / "case" / "metrics.jsonl")
    assert records[-1]["status"] == "failed"


def test_metrics_fields_complete(tmp_path: Path) -> None:
    root = tmp_path / "case"
    assert _import(root, _make_pdf(tmp_path)) == 0

    records = _read_jsonl(root / "metrics.jsonl")
    assert records
    for record in records:
        assert REQUIRED_METRIC_FIELDS <= set(record)
    assert records[-1]["pdf_pages"] == 5


def test_duplicate_import_records_zero_growth(tmp_path: Path) -> None:
    root = tmp_path / "case"
    pdf = _make_pdf(tmp_path)

    assert _import(root, pdf) == 0
    assert _import(root, pdf) == 0

    imports = [
        r for r in _read_jsonl(root / "probe-results.jsonl") if r["phase"] == "import"
    ]
    assert len(imports) == 2
    assert imports[1]["duplicate"] is True
    assert imports[1]["pages_delta"] == 0


def test_consistency_failure_returns_nonzero(tmp_path: Path) -> None:
    root = tmp_path / "case"
    assert _import(root, _make_pdf(tmp_path)) == 0
    victim = next((root / "data" / "pages").rglob("*.png"))
    victim.unlink()  # simulate damage: checker must fail (probe never repairs)

    assert probe.main(["--root", str(root), "consistency"]) == 1


def test_search_over_limit_reports_total_and_truncation(tmp_path: Path) -> None:
    root = tmp_path / "case"
    assert _import(root, _make_pdf(tmp_path)) == 0

    assert probe.main(["--root", str(root), "search", "--query", "SCALE", "--limit", "2"]) == 0
    records = [
        r for r in _read_jsonl(root / "probe-results.jsonl") if r["phase"] == "search"
    ]
    latest = records[-1]
    assert latest["returned"] == 2
    assert latest["total_hits"] == 5
    assert latest["truncated_at_limit"] is True


def test_probe_works_without_network(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    def _no_network(*_args: object, **_kwargs: object) -> object:
        raise OSError("network disabled by test")

    monkeypatch.setattr(socket, "create_connection", _no_network)
    monkeypatch.setattr(socket.socket, "connect", _no_network)

    root = tmp_path / "case"
    assert _import(root, _make_pdf(tmp_path)) == 0
    assert probe.main(["--root", str(root), "status"]) == 0
    assert probe.main(["--root", str(root), "consistency"]) == 0


def test_probe_leaves_no_processes_and_formal_untouched(tmp_path: Path) -> None:
    root = tmp_path / "case"
    assert _import(root, _make_pdf(tmp_path)) == 0
    # Everything the probe wrote lives under the isolated root:
    for artifact in (
        root / "data" / "database" / "knowledge.db",
        root / "metrics.jsonl",
        root / "probe-results.jsonl",
    ):
        assert artifact.is_file()
